#Connection to DB
spring:
  datasource: 
    password: jeep
    username: jeep
    url: jdbc:mysql://localhost:3306/jeep
#Logging Info
logging:
  level:
    root: warn
    '[com.promineotech]': debug
